#!/usr/bin/env bash
# Lovingly stolen from Tris/Oatman's gist https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5

# A rebuild script that commits on a successful build
set -e

# cd to your config dir
pushd ~/src/nixie_nodes/

hostname=$(hostname -s)

# Edit your config
$EDITOR nodes/$hostname/configuration.nix

# Early return if no changes were detected (thanks @singiamtel!)
if git diff --quiet ; then
    echo "No changes detected, exiting."
    popd
    exit 0
fi

# Autoformat your nix file
alejandra . &>/dev/null \
  || ( alejandra . ; echo "formatting failed!" && exit 1)

# Shows your changes
git diff -U0 *.nix

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo nixos-rebuild --flake .#$hostname switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Commit all changes witih the generation metadata
git commit -am "$hostname: $current"

# Back to where you were
popd
