#!/usr/bin/env bash
#
# A rebuild script that commits on a successful build
# Lovingly stolen from Tris/Oatman's gist https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5
set -e

# cd to your config dir
pushd ~/src/nixie_nodes/nodes/ddn

# Edit your config
$EDITOR flake.nix

# Early return if no changes were detected (thanks @singiamtel!)
if git diff --quiet ; then
    echo "No changes detected, exiting."
    popd
    exit 0
fi

# Autoformat your nix files
alejandra . >/dev/null

# Shows your changes
git diff -U0 *.nix

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
darwin-rebuild switch --flake  ~/src/nixie_nodes/nodes/ddn
#sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)

# Get current generation metadata
current=$(darwin-rebuild --list-generations | grep current)

# Commit all changes witih the generation metadata
git commit -am "$current"

# Back to where you were
popd

# Notify all OK!
osascript -e 'display notification "Rebuild Completed Succesfully" with title "Nix-Darwin"'
